---
title: "Identifying best age markers"
author: "Luke Hayden"
output: html_document
---

#Setup
###Packages
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#source("https://bioconductor.org/biocLite.R")
#biocLite("DESeq2")
#source("https://bioconductor.org/biocLite.R")
#biocLite("DESeq2")

library(ggplot2)
library(rmarkdown)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(scales)
library(ggbiplot)
library(devtools)
library(gtools)
library(Rmisc)
library(dplyr)
library(tidyr)


```

###Data Import

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}
setwd("~/Documents/nstringnov17")
load(file="nov17main_data.rdata")
```

#What is our best set of markers?


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- t(subset(t(ctg1to9), sampleinfo$sex == "F"& sampleinfo$qual == "ok"& sampleinfo$exp == "OvY" & sampleinfo$ctg>2& sampleinfo$type %in% c("O", "Y")& sampleinfo$size== "P" ))

si <- subset(sampleinfo, sampleinfo$sample %in% colnames(md))
old <- t(subset(t(md), si$age == "O"))
young <- t(subset(t(md), si$age == "Y"))
regen <- t(subset(t(ctg1to9), sampleinfo$type == "OR" & sampleinfo$qual == "ok"))





nmd <- as.data.frame(md/rowMeans(md))
nmd$name <- rownames(nmd)
nmd$sname <- substr(nmd$name, 1,2)

oy <- cbind(old, young)
t.result <-  apply(oy, 1, function (x) t.test(x[1:ncol(old)],x[ncol(old)+1: ncol(oy)]))


nmd$p_value <- unlist(lapply(t.result, function(x) x$p.value))

nmd <- left_join(nmd, geneinf, by="name")



nmd$YvOl2fc <- foldchange2logratio(foldchange(rowMeans(young), rowMeans(old)))
nmd$ROvOl2fc <- foldchange2logratio(foldchange(rowMeans(regen), rowMeans(old)))

nmd$chosen <- nmd$p_value < 0.05 & sign(nmd$transl2fc) == sign(nmd$YvOl2fc)


p=ggplot(nmd, aes(y=p_value, x=YvOl2fc, fill=chosen))  +
  scale_shape_manual(values=c(21,22))+
  geom_point(shape=21, colour="black")+ 
  theme_bw()+
  scale_fill_manual(values=c("darkgrey", "orange"), name="",breaks=c(T,F), labels=c("chosen markers", "other")) +
  scale_colour_manual(values=c("red3", "black"))+
  xlab("Absolute Young vs Old Log2Foldchange") +
  ylab("Old vs young p-value")+
  ggtitle(paste(sum(nmd$chosen), " markers: new optimised set"))+
    geom_hline(linetype=2, yintercept = 0.05)
  

ggsave(plot=p, filename="whichmark.pdf", device="pdf", height=2.5, width=8)

```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
nmd$sname <- factor(nmd$sname, levels=nmd$sname[order(nmd$p_value)])

mnmd <- gather(nmd, key=sample, value=normexp, O2a:LFPC)
mnmd$age <- ifelse(mnmd$sample %in% colnames(young), "young", "old")


ggplot(mnmd, aes(x= sname, y=normexp, colour=age)) +
  theme_minimal()+
  geom_point(size=3, shape=95)+
 stat_summary()+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size=4))+
  geom_text(colour="black",label="*", data=nmd,inherit.aes=FALSE,  aes(alpha=chosen, x=sname, y=8))+
  geom_text(colour="forest green",label="*", data=nmd,inherit.aes=FALSE,  aes(alpha=in61, x=sname, y=9))+
  scale_alpha_manual(values=c(0,1))+
  guides(alpha=F)+
  xlab("Marker") +
  ylab("Normalised Expression")


```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


ggplot(mnmd, aes(x= sname, y=normexp, colour=age)) +
  theme_minimal()+
  geom_boxplot(outlier.shape = NA)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size=4))+
  geom_text(colour="black",label="*", data=nmd,inherit.aes=FALSE,  aes(alpha=chosen, x=sname, y=8))+
  geom_text(colour="forest green",label="*", data=nmd,inherit.aes=FALSE,  aes(alpha=in61, x=sname, y=9))+
  scale_alpha_manual(values=c(0,1))+
  guides(alpha=F)+
  xlab("Marker") +
  ylab("Normalised Expression")



```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
minf <- nmd[,colnames(nmd) %in% c("name"   ,   "sname"    , "p_value",   "transl2fc", "dir"  ,     "in61"    ,  "YvOl2fc"  , "ROvOl2fc",  "chosen" )]





```


#Compare old vs new marker set

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

log <- sampleinfo$sex =="F" & sampleinfo$ctg %in% c(3,4,5,7) & sampleinfo$qual == "ok" & sampleinfo$reg == "" & sampleinfo$age != "N"

bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% geneinf$name[geneinf$in61==T])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups


a=ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA of Old vs Young (females): 61 chosen markers")+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))



bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% nmd$name[nmd$chosen==TRUE])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

b=ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle(paste("PCA of Old vs Young (females):", nrow(bcmin) ," newly chosen markers"))+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))



bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% nmd$name[nmd$chosen==TRUE ])

bcmin <- subset(bcmin, rownames(bcmin) %in% geneinf$name[geneinf$in61==T])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

c=ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle(paste("PCA of Old vs Young (females):", nrow(bcmin) ," markers in both lists"))+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))


multiplot(a,c,b, cols=2)


a




bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% nmd$name[nmd$chosen==TRUE])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = T, circle = TRUE, var.axes=FALSE, groups=bc.groups)+
  ggtitle(paste("PCA of Old vs Young (females):", nrow(bcmin) ," newly chosen markers"))+
    theme_bw() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"), labels=c("Old", "Young"), name="Age")+
  theme(plot.title=element_text(size=8,face="bold"))



```

Without Nikos' samples:

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

log <- sampleinfo$sex =="F" & sampleinfo$ctg %in% c(3,4,5,7) & sampleinfo$qual == "ok" & sampleinfo$reg == "" & sampleinfo$age != "N" &sampleinfo$prep == "Luke"

bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% geneinf$name[geneinf$in61==T])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups


a=ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA of Old vs Young (females): 61 chosen markers")+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))



bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% nmd$name[nmd$chosen==TRUE])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

b=ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle(paste("PCA of Old vs Young (females):", nrow(bcmin) ,"newly chosen markers"))+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))


p=ggbiplot(bc.pca, obs.scale = 1, var.scale = 0.5, ellipse = F, circle = F,varname.size = 0,var.axes=T, groups=bc.groups)+
  ggtitle(paste("PCA of Old vs Young (females):", nrow(bcmin) ," chosen markers"))+
    theme_bw() +
  geom_point(shape=21, size=5, aes(fill=groups))+
  scale_fill_manual(values=c("cornflower blue", "red3", "black"), labels=c("Old", "Young"), name="Age")+
  theme(plot.title=element_text(size=8,face="bold"))


ggsave(plot=p, filename="pca50.pdf", device="pdf", height=3, width=6)




bcmin <- ctg1to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% nmd$name[nmd$chosen==TRUE ])

bcmin <- subset(bcmin, rownames(bcmin) %in% geneinf$name[geneinf$in61==T])
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

c=ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle(paste("PCA of Old vs Young (females):", nrow(bcmin) ," markers in both lists"))+
    theme_minimal() +
  scale_colour_manual(values=c("cornflower blue", "red3", "black"))+
  theme(plot.title=element_text(size=8,face="bold"))

multiplot(a,c,b, cols=2)


```


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
gnmd <- subset(nmd, nmd$chosen== TRUE)

ggplot(data=nmd, aes(x=YvOl2fc, y=ROvOl2fc, label=sname, colour=chosen))+
  geom_hline(yintercept=0, colour="black")+
  geom_vline(xintercept=0, colour="black")+
  theme_minimal()+
  xlim(-5,+5)+
  ylim(-5,5)+
 scale_colour_manual(values= c("grey", "forest green"), name="Marker", labels=c("other","chosen"))+
  xlab("Young vs Old Log2 Fold Change") +
  ylab("Regenerated vs Old Log2 Fold Change")+
#  geom_rect(inherit.aes=FALSE, xmin=-10, ymin=-10, xmax=0, ymax=0, fill="yellow", alpha=0.004)+
#  geom_rect(inherit.aes=FALSE,xmin=0, ymin=0, xmax=10, ymax=10, fill="yellow", alpha=0.004)+
  geom_point( size=1.5)+


  geom_abline(inherit.aes=FALSE, intercept=0, slope=1, linetype=2)+
  theme(    plot.background = element_rect(fill = "transparent",colour = "transparent") )+
  coord_fixed(ratio=1)
  

```

#Output marker info
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
minf$chosenand <- minf$in61 &minf$chosen

save(minf ,file="markerchoiceinfo.rdata")





```



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

md <- t(subset(t(ctg1to9), sampleinfo$sex == "F"& sampleinfo$qual == "ok"&  sampleinfo$ctg>2& sampleinfo$type %in% c("O", "Y", "OR")& sampleinfo$size== "P" ))

si <- subset(sampleinfo, sampleinfo$sample %in% colnames(md))

nmd <- as.data.frame(md/rowMeans(md))

nmd$name <- rownames(nmd)
nmd <- left_join(nmd, minf, by="name")

nmd$sname <- factor(nmd$sname, levels=nmd$sname[order(nmd$p_value)])

mnmd <- gather(nmd, key=sample, value=normexp, O2a:Ereg)
mnmd <- left_join(mnmd, sampleinfo, by="sample")


```



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

gmnmd <- subset(mnmd, mnmd$chosenand == T & mnmd$reg == "")


ggplot(gmnmd, aes(x= sname, y=normexp, colour=type)) +
  theme_bw()+
  geom_point(size=2)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size=6))+
  xlab("Marker") +
  ylab("Normalised Expression")


ggplot(gmnmd, aes(x= sname, y=normexp, fill=type)) +
  theme_bw()+
  geom_boxplot(outlier.shape=NA)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_fill_manual(values=c("cornflower blue", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size=8))+
  xlab("Marker") +
  ylab("Normalised Expression")

```




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

gmnmd <- subset(mnmd, mnmd$chosenand == T)


ggplot(gmnmd, aes(x= sname, y=normexp, colour=type)) +
  theme_bw()+
  geom_point(size=2)+
  scale_y_continuous(trans="log2")+
  facet_grid(~dir, space="free",scales="free" )+
#  geom_boxplot(outlier.shape = NA)+
  scale_colour_manual(values=c("cornflower blue", "forest green", "red3"))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size=6))+
  xlab("Marker") +
  ylab("Normalised Expression")


```







