---
title: "NanoStringNov17"
author: "Luke Hayden"
date: "24 Novembre 2017"
output: html_document
---


#Packages
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#source("https://bioconductor.org/biocLite.R")
#biocLite("DESeq2")
#source("https://bioconductor.org/biocLite.R")
#biocLite("DESeq2")

library(ggplot2)
library(DESeq2)
library(rmarkdown)
library(pracma)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(scales)
library(ggbiplot)
library(gtools)
library(devtools)
library(NanoStringNorm)
library(ggthemes)
library(grid)
library(gridExtra)
library(sjstats)


multiplot <- function(..., plotlist = NULL, file, cols = 1, layout = NULL) {
  require(grid)
  
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  if (is.null(layout)) {
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots == 1) {
    print(plots[[1]])
    
  } else {
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    for (i in 1:numPlots) {
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

#Data Import

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


gm <- read.csv("gmark.csv")

setwd("~/Documents/nstringnov17/ctg5and6")
ct5and6.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg5hi")
ct5and6hi.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg7and8")
ct7and8.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg7and8hi")
ct7and8hi.raw <- read.markup.RCC()

setwd("~/Documents/nstringnov17/ctg3and4")

ct3and4.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg9")

ct9.raw <- read.markup.RCC()

````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}
codeset <- read.table("CodeSet.txt")
codeset$shortname <- substr(codeset$Customer_Identifier, 1,2)
Cht <- read.table("CodeSetCountdata.txt")




ctg5and6.norm <- NanoStringNorm(x = ct5and6.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);


ctg5and6hi.norm <- NanoStringNorm(x = ct5and6hi.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg7and8.norm <- NanoStringNorm(x = ct7and8.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg7and8hi.norm <- NanoStringNorm(x = ct7and8hi.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg3and4.norm <- NanoStringNorm(x = ct3and4.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg9.norm <- NanoStringNorm(x = ct9.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

````
#Normalisation
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}

colnames(ctg5and6.norm) <- c("SFPA", "SFPB", "LFPA", "LFPB", "SMPA", "SMPB", "LMPA", "LMPB", "LMIA", "LMIB", "LMIC", "LMID", "Abef", "Aun", "Areg", "Bbef", "Bun", "Breg", "Cbef", "Cun", "Creg", "Dbef", "Dun", "Dreg")

colnames(ctg5and6hi.norm) <-  c("SFPA", "SFPB", "LFPA", "LFPB", "SMPA", "SMPB", "LMPA", "LMPB", "LMIA", "LMIB", "LMIC", "LMID", "Abef", "Aun", "Areg", "Bbef", "Bun", "Breg", "Cbef", "Cun", "Creg", "Dbef", "Dun", "Dreg")


colnames(ctg7and8.norm) <- c("SFPC","SFPD", "LFPC", "LFPD", "SMPC", "SMPD","LMPC", "LMPD", "0mPA", "0mPB", "10mPA", "20mPA", "Ebef", "Eun", "Ereg", "Fbef", "Fun", "Freg", "Gbef", "Gun", "Greg", "LFIA", "LFIB", "20mPB")

colnames(ctg7and8hi.norm) <-c("SFPC","SFPD", "LFPC", "LFPD", "SMPC", "SMPD","LMPC", "LMPD", "0mPA", "0mPB", "10mPA", "20mPA", "Ebef", "Eun", "Ereg", "Fbef", "Fun", "Freg", "Gbef", "Gun", "Greg", "LFIA", "LFIB", "20mPB")


colnames(ctg3and4.norm) <- c("O1a", "O2a", "Y1a", "Y2a", "OR1a", "OR2a", "YR1a", "YR2a", "FY5a", "FY6a", "FO5a", "FO7a", "O1b", "O2b", "Y1b", "Y2b", "OR1b", "OR2b", "YR1b", "YR2b", "FY7", "FY8", "FO8", "FO9")

colnames(ctg9.norm) <- c("LFIC", "LFID", "OmID", "10mIA", "n", "20mIC", "Ibef", "Iun", "Ireg", "Kbef", "Kun", "Kreg")

ctg3to8 <- cbind(ctg3and4.norm, ctg5and6hi.norm, ctg7and8.norm)

ctg3to9 <- cbind(ctg3and4.norm, ctg5and6hi.norm, ctg7and8hi.norm, ctg9.norm)

sampleinfo <- data.frame(

sample=colnames(ctg3to9), 
                         
sex=c(rep("F", 28), rep("M", 8), rep("F", 16), rep("M", 4), rep("F", 28)), 

age=c(rep(c("O", "O", "Y", "Y", "O", "O", "Y", "Y","Y", "Y", "O", "O"), 2), c("Y", "Y", "O", "O", "Y", "Y", "O", "O", "O", "O", "O", "O", rep("O", 12)), c("Y", "Y", "O", "O", "Y", "Y", "O", "O", "N", "N", "N", "N"), rep("O", 11), c("N", "O", "O",  "N", "N", "N", "N", "O", "O", "O", "O", "O", "O")), 

reg=c(rep(c(rep("", 4), rep("R", 4), rep("", 4)), 2), c(rep("", 12), rep(c("", "", "R"),4 )   ), c(rep("", 12), rep(c("", "", "R"),3 )   ), rep("",15 )) , 

ctg=c(rep("3", 12), rep("4", 12), rep("5", 12), rep("6", 12), rep("7", 12), rep("8", 12), rep("9", 12))  )

sampleinfo$type <- paste(sampleinfo$age, sampleinfo$reg, sep="")
sampleinfo$qual <- "ok"
sampleinfo$qual[c(1,7,8, 25, 43, 52, 66,77,80,83)] <- "bad"


```
#Sample Quality

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}
#all <- ctg3to8
#all$isg <- rownames(ctg3to8) %in% gm
mc36 <- melt(ctg3to9)
mc36$exp <- mc36$value > 1
mc36$isg <- mc36$Var1 %in% gm$marker
mc36$qual <- mc36$Var2 %in% sampleinfo$sample[sampleinfo$qual == "ok"]
ggplot(mc36, aes(y=value, x=Var1, colour=qual)) +geom_point(alpha=0.3) +facet_wrap(~Var2) +scale_y_log10() +scale_colour_manual(values=c("red3", "dark blue")) +theme(axis.text.x = element_blank())



```

#Effect of high vs lower sensitivity
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
mc5 <- melt(ctg5and6.norm)
mc5h <- melt(ctg5and6hi.norm)
mc5h$hival <- mc5$value

ggplot(data=mc5h, aes(x=value, y=hival, colour=Var2)) +geom_point() +facet_wrap(~Var2, ncol=6) +scale_x_log10() +scale_y_log10()
```

#Is the age signal retained
Two low quality samples removed
Females only:

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

log <- sampleinfo$sex =="F" & sampleinfo$ctg %in% c(3,4,5,7) & sampleinfo$qual == "ok" & sampleinfo$reg == "" & sampleinfo$age != "N"


bcmin <- ctg3to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% gm$marker)
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA of O vs Y: 61 chosen markers")+ scale_colour_manual(values=c("cornflower blue", "red3", "black"))
```

Now including males:

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

log <- sampleinfo$ctg %in% c(3,4,5,7) & sampleinfo$qual == "ok" & sampleinfo$reg == ""& sampleinfo$age != "N"


bcmin <- ctg3to9[,log== TRUE]
bcmin.groups <- subset(paste(sampleinfo$type, sampleinfo$sex), log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% gm$marker)
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA of O vs Y: 61 chosen markers")+ scale_colour_manual(values=c("cornflower blue","dark blue",  "red3", "orangered"))
```

Males only: 
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

log <- sampleinfo$sex =="M" & sampleinfo$ctg %in% c(3,4,5,7) & sampleinfo$qual == "ok" & sampleinfo$reg == ""


bcmin <- ctg3to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% gm$marker)
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups

ggbiplot(bc.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(tbc), groups=bc.groups)+ggtitle("PCA of O vs Y: 61 chosen markers")+ scale_colour_manual(values=c("cornflower blue", "red3"))
```



#Age signal by marker
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
an <- ctg3to9
an <- subset(an, rownames(an) %in% gm$marker)
log <- sampleinfo$sex =="F" &  sampleinfo$qual == "ok" & sampleinfo$reg != "R"& sampleinfo$age != "N"
anf <- an[,log==TRUE]

anf <- anf/rowMeans(anf)

sif <- subset(sampleinfo, log)
colnames(anf) <- paste( sif$type, colnames(anf))
#anf <- rbind(anf, t(sif))
manf <- melt(anf)

manf$type <- substr(manf$Var2,1,2)
manf$mk <- substr(manf$Var1, 1,2)
manf$dir <- "upregulated with age"
manf$dir[manf$Var1 %in% gm$marker[gm$dir =="downregulated with age"]] <- "downregulated with age"
manf$dm <- paste(substr(manf$dir, 1,1), manf$mk)

ggplot(manf, aes(x=dm, y=value, colour=type)) +
  geom_point(shape=95, size=4)  +
  scale_color_manual(values=c("cornflower blue", "red3"), name= "Age") +
  theme(axis.text.x = element_text(angle = 60, hjust =1, size=7))+
  xlab("Marker") +
  ylab("Expression level (Normalised to mean)") +
  scale_y_continuous(trans='log2', breaks=c(0,0.062,0.125,0.25,0.5,1,2,4))


ggplot(manf, aes(x=mk, y=value, colour=type, fill=dir)) +
  geom_boxplot(outlier.alpha = 0)+
  scale_y_continuous(trans='log2', breaks=c(0,0.062,0.125,0.25,0.5,1,2,4))+
  geom_hline(yintercept=1, colour = "black", linetype=2) +
  scale_fill_manual(values=c("white", "dark grey"))  +
  scale_color_manual(values=c("cornflower blue", "red3")) +
  theme(axis.text.x = element_text(angle = 60, hjust =0.5, size=7)) +
  facet_wrap(~dir, ncol=1, scales="free_x") +
  xlab("Marker") +
  ylab("Expression level (Normalised to mean)")
```
#Regen effect on PCA
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


log <- sampleinfo$sex =="F" & sampleinfo$ctg %in% c(3,4,5,7) & sampleinfo$qual == "ok" & sampleinfo$reg == ""& sampleinfo$age != "N"


bcmin <- ctg3to9[,log== TRUE]
bcmin.groups <- subset(sampleinfo$type, log==TRUE)
bcmin <- subset(bcmin, rownames(bcmin) %in% gm$marker)
tbc <- t(bcmin)
tbc <- tbc[,colSums(tbc) > 0]
bc.pca <- prcomp(tbc,center = TRUE,scale. = TRUE) 
bc.groups <- bcmin.groups
rg <-ctg3to8[,c(5,6,17,18,37:42,44:48,61:69)]
rg <- subset(rg, rownames(rg) %in% gm$marker)
rg.groups <- sampleinfo$type[c(5,6,17,18,37:42,44:48,61:69)]

rg.sc <- scale(t(rg), center= bc.pca$center)
rg.pred <- rg.sc %*% bc.pca$rotation 


rgd.pca <- bc.pca
rgd.pca$x <- rbind(bc.pca$x, rg.pred)
                   
                   
rgd.groups <- append(bcmin.groups, rg.groups)                

ggbiplot(rgd.pca, obs.scale = 1, var.scale = 1, ellipse = FALSE, circle = TRUE, var.axes=FALSE, labels=rownames(rgd.pca$x), groups=rgd.groups, varname.abbrev = TRUE)+ theme(legend.direction = 'horizontal', legend.position = 'top')+ggtitle("PCA Old vs Young + regenerated projected")+ scale_colour_manual(values=c("cornflower blue", "forest green", "red3"))

````

#Regen effect on per marker basis
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
an <- ctg3to9
an <- subset(an, rownames(an) %in% gm$marker)
log <- sampleinfo$sex =="F" &  sampleinfo$qual == "ok" & sampleinfo$type != "YR"& sampleinfo$age != "N"
anf <- an[,log==TRUE]
anf <- anf/rowMeans(anf)

sif <- subset(sampleinfo, log)
colnames(anf) <- paste( sif$type, colnames(anf))
#anf <- rbind(anf, t(sif))
manf <- melt(anf)

manf$type <- substr(manf$Var2,1,2)
manf$mk <- substr(manf$Var1, 1,2)
manf$dir <- "upregulated with age"
manf$dir[manf$Var1 %in% gm$marker[gm$dir =="downregulated with age"]] <- "downregulated with age"
manf$dm <- paste(substr(manf$dir, 1,1), manf$mk)

ggplot(manf, aes(x=dm, y=value, colour=type)) +
  geom_point(shape=95, size=4)  +
  scale_color_manual(values=c("cornflower blue", "forest green",  "red3"), name= "Age") +
  theme(axis.text.x = element_text(angle = 60, hjust =1, size=7))+
  xlab("Marker") +
  ylab("Expression level (Normalised to mean)") +
  scale_y_continuous(trans='log2', breaks=c(0,0.062,0.125,0.25,0.5,1,2,4))


ggplot(manf, aes(x=mk, y=value, colour=type, fill=dir)) +
  geom_boxplot(outlier.shape=NA)+
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4))+
  geom_hline(yintercept=1, colour = "black", linetype=2) +
  scale_fill_manual(values=c("white", "dark grey"))  +
  scale_color_manual(values=c("cornflower blue", "forest green",  "red3")) +
  theme(axis.text.x = element_text(angle = 60, hjust =0.5, size=7)) +
  facet_wrap(~dir, ncol=1, scales="free_x")


ggplot(manf, aes(x=value, fill=type)) +
  geom_density(alpha=0.5)  +
  scale_fill_manual(values=c("cornflower blue",  "forest green","red3" ), name= "Age") +
  scale_x_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4))+
  facet_wrap(~dir, ncol=1  )

````


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}



````
#Regeneration experiment in detail
Only our regen sets

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
an <- ctg3to9
an <-subset(an, rownames(an) %in% gm$marker)
re <- an[,c(37:48,61:69, 79:84)]
re <- re/rowMeans(re)
msi <- subset(sampleinfo, sampleinfo$sample %in% colnames(re))
re <- re[, msi$qual=="ok"]
                


mre <- melt(re)
mre$sample <- substr(mre$Var2,1,1)
mre$type <- substr(mre$Var2,2,length(mre$Var2))
mre$mk <- substr(mre$Var1, 1,2)
mre$dir <- "upregulated with age"
mre$dir[mre$Var1 %in% gm$marker[gm$dir =="downregulated with age"]] <- "downregulated with age"
mre$md <- paste(substr(mre$dir, 1,2), mre$mk)

ggplot(data=mre, aes(colour=type, x=md, y=value)) +
  geom_point() +
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4))+
  geom_hline(yintercept=1, colour = "black", linetype=2)+
#  facet_wrap(~sample, ncol=1) +
  scale_color_manual(values=c("cornflower blue", "forest green",  "dark blue"))+
  theme(axis.text.x = element_text(angle = 60, hjust=1))

````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
ggplot(data=mre, aes(colour=type, x=md, y=value, fill=dir)) +
  geom_boxplot(outlier.shape=NA) +
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4))+
  geom_hline(yintercept=1, colour = "black", linetype=2)+
#  facet_wrap(~sample, ncol=1) +
  scale_color_manual(values=c("cornflower blue", "forest green",  "dark blue")) +
  theme(axis.text.x = element_text(angle = 60, hjust=1))+
  scale_fill_manual(values=c("white", "dark grey")) 


ggplot(data=mre, aes(colour=type, x=md, y=value)) +
  geom_point() +
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4))+
  geom_hline(yintercept=1, colour = "black", linetype=2)+
#  facet_wrap(~sample, ncol=1) +
  scale_color_manual(values=c("cornflower blue", "forest green",  "dark blue"))+
  theme(axis.text.x = element_text(angle = 60, hjust=1))+
  facet_wrap(~sample)



ggplot(data=mre, aes(fill=type, x=value)) +
  geom_density(alpha=0.5) +
  scale_x_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4))+
  geom_vline(xintercept=1, colour = "black", linetype=2)+
  scale_fill_manual(values=c("cornflower blue", "forest green",  "dark blue")) +
  facet_wrap(~dir, ncol=1)

````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

an <-subset(an, rownames(an) %in% gm$marker)
re <- as.data.frame(an[,c(37:48,61:69)])
re$dir <- subset(gm, gm$dir != "housekeeping")$dir
re$marker <- rownames(re)


mre <- melt(re, id.vars=c("dir", "marker"))
mre$sample <- substr(mre$variable, 1,1)
mre$type <- substr(mre$variable, 2, length(mre$variable))

cmre <- data.frame(marker = mre$marker[mre$type == "bef"], sample =mre$sample[mre$type == "bef"], dir = mre$dir[mre$type == "bef"],bef= mre$value[mre$type == "bef"], un = mre$value[mre$type == "un"], reg =mre$value[mre$type == "reg"])



cmren <- data.frame(marker = mre$marker[mre$type == "bef"], sample =mre$sample[mre$type == "bef"], dir = mre$dir[mre$type == "bef"],bef= mre$value[mre$type == "bef"]/mre$value[mre$type == "bef"], un = mre$value[mre$type == "un"]/mre$value[mre$type == "bef"], reg =mre$value[mre$type == "reg"]/mre$value[mre$type == "bef"])
cmren <- subset(cmren, cmren$bef ==1)

mcmren <- melt(cmren, id.vars=c("marker", "sample", "dir"))
mcmren$md <- paste(substr(mcmren$dir,1,2), substr(mcmren$marker,1,2))

ggplot(mcmren, aes(x=md, y=value, fill=md, colour=variable)) +
  geom_point() +
  scale_color_manual(values=c("cornflower blue", "forest green",  "dark blue"))+
  geom_vline(xintercept=1, colour = "black", linetype=2)+
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4)) +
  theme(axis.text.x = element_text(angle = 60, hjust=1))+
  facet_wrap(~dir, scales="free_x")

````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


ggplot(mcmren, aes(x=md, y=value,  colour=variable, fill=dir)) +
  geom_boxplot(outlier.shape=NA) +
  scale_colour_manual(values=c("cornflower blue" , "dark blue", "forest green"))+
#  scale_fill_manual(values=c("cornflower blue" , "dark blue", "forest green"))+
  geom_hline(yintercept=1, colour = "black", linetype=2)+
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4)) +
  theme(axis.text.x = element_text(angle = 60, hjust=1))+
  scale_fill_manual(values=c("white", "dark grey")) 
```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

log <- 1:ncol(ctg3to9) %in% c(2,5:6, 13:14)
ovr <- as.data.frame(ctg3to9[,log==TRUE])
ovrsi <- sampleinfo[log==TRUE,]

ovr$regmean <- rowMeans(data.frame(ovr$OR1a, ovr$OR2a))
ovr$omean <- rowMeans(data.frame(ovr$O2a, ovr$O1b, ovr$O2b))
ovr <- subset(ovr, rownames(ovr) %in% gm$marker)

ovr$regeff <- ovr$regmean/ovr$omean


an <-subset(an, rownames(an) %in% gm$marker)
re <- as.data.frame(an[,c(37:48,61:69)])
re$dir <- subset(gm, gm$dir != "housekeeping")$dir
re$marker <- rownames(re)

re$regeff <- ovr$regeff

mre <- melt(re, id.vars=c("dir", "marker", "regeff"))
mre$sample <- substr(mre$variable, 1,1)
mre$type <- substr(mre$variable, 2, length(mre$variable))


cmren <- data.frame(marker = mre$marker[mre$type == "bef"], sample =mre$sample[mre$type == "bef"], dir = mre$dir[mre$type == "bef"],bef= mre$value[mre$type == "bef"]/mre$value[mre$type == "bef"], un = mre$value[mre$type == "un"]/mre$value[mre$type == "bef"], reg =mre$value[mre$type == "reg"]/mre$value[mre$type == "bef"], regeff = mre$regeff)
cmren <- subset(cmren, cmren$bef ==1)

mcmren <- melt(cmren, id.vars=c("marker", "sample", "dir", "regeff"))
mcmren$md <- paste(substr(mcmren$dir,1,2), substr(mcmren$marker,1,2))

ggplot(mcmren, aes(x=md, y=value,  colour=variable, fill=dir)) +
  geom_boxplot(outlier.shape=NA) +
  scale_colour_manual(values=c("cornflower blue" , "dark blue", "forest green"))+
  geom_hline(yintercept=1, colour = "black", linetype=2)+
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4)) +
  theme(axis.text.x = element_text(angle = 60, hjust=1))+
  scale_fill_manual(values=c("white", "dark grey")) +
  geom_point(aes(x=md, y=regeff), colour="black", fill="forest green", shape=21)


x <-tapply(cmren$reg, cmren$marker, summary)



ggplot(cmren, aes(x=reg, y=regeff)) +geom_point() +scale_x_log10() +scale_y_log10()



ggplot(cmren, aes(x=reg, y=regeff)) +geom_point()+scale_x_log10() +scale_y_log10()


```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

ggplot(mcmren, aes(x=md, y=value,colour=variable)) +
  geom_point( alpha=0.5) +
  scale_colour_manual(values=c("cornflower blue" , "dark blue", "forest green"))+
  geom_hline(yintercept=1, colour = "black", linetype=2)+
  scale_y_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4)) +
  theme(axis.text.x = element_text(angle = 60, hjust=1))+
  facet_wrap(~dir, scales="free_x", ncol=1)


ggplot(mcmren, aes(x=value,fill=variable)) +
  geom_density( alpha=0.5) +
  scale_fill_manual(values=c("cornflower blue" , "dark blue", "forest green"))+
  geom_vline(xintercept=1, colour = "black", linetype=2)+
  scale_x_continuous(trans='log2', breaks=c(0,0.25,0.5,1,2,4)) +
  facet_wrap(~dir, scales="free_x", ncol=1)
```




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
cmre <- data.frame(marker = mre$marker[mre$type == "bef"], sample =mre$sample[mre$type == "bef"], dir = mre$dir[mre$type == "bef"],bef= mre$value[mre$type == "bef"], un = mre$value[mre$type == "un"], reg =mre$value[mre$type == "reg"])



cmre <- subset (cmre, cmre$bef + cmre$un + cmre$reg != 0)
cmre$md <- paste(substr(cmre$dir,1,2), substr(cmre$marker,1,2))

ggplot(cmre, aes(x=md)) +
  geom_segment(aes(x=md, xend=md, y=bef, yend=reg), colour="forest green", alpha=0.3) +
  geom_segment(aes(x=md, xend=md, y=bef, yend=un), colour="dark blue", alpha=0.3)+
  scale_y_continuous(trans='log2')  +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

cmren$md <- paste(substr(cmren$dir,1,2), substr(cmren$marker,1,2))

ggplot(cmren, aes(x=md)) +
  geom_segment(aes(x=md, xend=md, y=bef, yend=reg), colour="forest green", alpha=0.3) +
  geom_segment(aes(x=md, xend=md, y=bef, yend=un), colour="dark blue", alpha=0.3)+
  geom_point(aes(x=md, y=un), colour="dark blue")+
  geom_point(aes(x=md, y=reg), colour="forest green")+
  scale_y_continuous(trans='log2')  +
  theme(axis.text.x = element_text(angle = 60, hjust=1))

```