---
title: "NanoStringNov17"
author: "Luke Hayden"
date: "24 November 2017"
output: html_document
---

#Setup
###Packages
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
#source("https://bioconductor.org/biocLite.R")
#biocLite("DESeq2")
#source("https://bioconductor.org/biocLite.R")
#biocLite("DESeq2")

library(ggplot2)
library(DESeq2)
library(rmarkdown)
library(pracma)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(scales)
library(ggbiplot)
library(gtools)
library(devtools)
library(NanoStringNorm)
library(ggthemes)
library(grid)
library(gridExtra)
library(sjstats)
library(matrixStats)
library(gbutils)
library(class)
library(Rmisc)
```

###Data Import

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


gm <- read.csv("gmark.csv")

setwd("~/Documents/nstringnov17/ctg5and6")
ct5and6.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg5hi")
ct5and6hi.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg7and8")
ct7and8.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg7and8hi")
ct7and8hi.raw <- read.markup.RCC()

setwd("~/Documents/nstringnov17/ctg3and4")

ct3and4.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg1and2")

ct1and2.raw <- read.markup.RCC()


setwd("~/Documents/nstringnov17/ctg9")

ct9.raw <- read.markup.RCC()

````

###Normalisation

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}
codeset <- read.table("CodeSet.txt")
codeset$shortname <- substr(codeset$Customer_Identifier, 1,2)
Cht <- read.table("CodeSetCountdata.txt")

ctg1and2.norm <- NanoStringNorm(x = ct1and2.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg3and4.norm <- NanoStringNorm(x = ct3and4.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg5and6.norm <- NanoStringNorm(x = ct5and6.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg5and6hi.norm <- NanoStringNorm(x = ct5and6hi.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg7and8.norm <- NanoStringNorm(x = ct7and8.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg7and8hi.norm <- NanoStringNorm(x = ct7and8hi.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);


ctg9.norm <- NanoStringNorm(x = ct9.raw, anno = NA, CodeCount ='sum', Background ="mean", SampleContent ='housekeeping.sum', round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);



````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}

ctg5and6.unnorm <- NanoStringNorm(x = ct5and6.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg5and6hi.unnorm <- NanoStringNorm(x = ct5and6hi.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg7and8.unnorm <- NanoStringNorm(x = ct7and8.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg7and8hi.unnorm <- NanoStringNorm(x = ct7and8hi.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg3and4.unnorm <- NanoStringNorm(x = ct3and4.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);


ctg1and2.unnorm <- NanoStringNorm(x = ct1and2.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg9.unnorm <- NanoStringNorm(x = ct9.raw, anno = NA, CodeCount ='sum', Background ="mean",OtherNorm = "none", round.values = FALSE, take.log = FALSE,return.matrix.of.endogenous.probes = TRUE);

ctg1to9un <- cbind(ctg1and2.unnorm,ctg3and4.unnorm, ctg5and6hi.unnorm, ctg7and8hi.unnorm, ctg9.unnorm)
````

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}


colnames(ctg1and2.norm) <- c("C200", "C100", "C50", "C25", "C12", "C6", "CIA", "CIB", "FYA", "FOA", "MYA", "MOA","FYB",	"FOB",	"MYB",	"MOB",	"MOIA",	"MOIB","MOIC",	"MOID",	"CS1X",	"CS0.5X",	"CS0.25XA",	"CS0.25XB")
colnames(ctg1and2.unnorm) <- colnames(ctg1and2.norm) 

colnames(ctg3and4.norm) <- c("O1a", "O2a", "Y1a", "Y2a", "OR1a", "OR2a", "YR1a", "YR2a", "FY5a", "FY6a", "FO5a", "FO7a", "O1b", "O2b", "Y1b", "Y2b", "OR1b", "OR2b", "YR1b", "YR2b", "FY7", "FY8", "FO8", "FO9")
colnames(ctg3and4.unnorm) <- colnames(ctg3and4.norm) 

colnames(ctg5and6.norm) <- c("SFPA", "SFPB", "LFPA", "LFPB", "SMPA", "SMPB", "LMPA", "LMPB", "LMIA", "LMIB", "LMIC", "LMID", "Abef", "Aun", "Areg", "Bbef", "Bun", "Breg", "Cbef", "Cun", "Creg", "Dbef", "Dun", "Dreg")
colnames(ctg5and6.unnorm) <- colnames(ctg5and6.norm) 

colnames(ctg5and6hi.norm) <-  c("SFPA", "SFPB", "LFPA", "LFPB", "SMPA", "SMPB", "LMPA", "LMPB", "LMIA", "LMIB", "LMIC", "LMID", "Abef", "Aun", "Areg", "Bbef", "Bun", "Breg", "Cbef", "Cun", "Creg", "Dbef", "Dun", "Dreg")
colnames(ctg5and6hi.unnorm) <- colnames(ctg5and6hi.norm) 

colnames(ctg7and8.norm) <- c("SFPC","SFPD", "LFPC", "LFPD", "SMPC", "SMPD","LMPC", "LMPD", "0mPA", "0mPB", "10mPA", "20mPA", "Ebef", "Eun", "Ereg", "Fbef", "Fun", "Freg", "Gbef", "Gun", "Greg", "LFIA", "LFIB", "20mPB")
colnames(ctg7and8.unnorm) <- colnames(ctg7and8.norm) 

colnames(ctg7and8hi.norm) <-c("SFPC","SFPD", "LFPC", "LFPD", "SMPC", "SMPD","LMPC", "LMPD", "0mPA", "0mPB", "10mPA", "20mPA", "Ebef", "Eun", "Ereg", "Fbef", "Fun", "Freg", "Gbef", "Gun", "Greg", "LFIA", "LFIB", "20mPB")
colnames(ctg7and8hi.unnorm) <- colnames(ctg7and8hi.norm) 

colnames(ctg9.norm) <- c("LFIC", "LFID", "OmID", "10mIA", "n", "20mIC", "Ibef", "Iun", "Ireg", "Kbef", "Kun", "Kreg")
colnames(ctg9.unnorm) <- colnames(ctg9.norm) 

ctg3to9 <- cbind(ctg3and4.norm, ctg5and6hi.norm, ctg7and8hi.norm, ctg9.norm)

ctg1to9 <- cbind(ctg1and2.norm,ctg3and4.norm, ctg5and6hi.norm, ctg7and8hi.norm, ctg9.norm)


sampleinfo <- data.frame(

sample=colnames(ctg1to9), 
                         
sex=c(rep("M", 8), rep(c("F", "F", "M", "M"), 2), rep("M", 8), rep("F", 28), rep("M", 8), rep("F", 16), rep("M", 4), rep("F", 28)), 

age=c(rep("O",8), rep(c("Y","O","Y","O"),2),rep("O",8),  rep(c("O", "O", "Y", "Y", "O", "O", "Y", "Y","Y", "Y", "O", "O"), 2), c("Y", "Y", "O", "O", "Y", "Y", "O", "O", "O", "O", "O", "O", rep("O", 12)), c("Y", "Y", "O", "O", "Y", "Y", "O", "O", "N", "N", "N", "N"), rep("O", 11), c("N", "O", "O",  "N", "N", "N", "N", "O", "O", "O", "O", "O", "O")), 

reg=c(rep("",24), rep(c(rep("", 4), rep("R", 4), rep("", 4)), 2), c(rep("", 12), rep(c("", "", "R"),4 )   ), c(rep("", 12), rep(c("", "", "R"),3 )   ), rep("",11 ), "R", "", "", "R") , 

ctg=c(rep(1, 12), rep(2, 12),rep(3, 12), rep(4, 12), rep(5, 12), rep(6, 12), rep(7, 12), rep(8, 12), rep(9, 12)),

size= c(rep("P",6), "I", "I", rep("P",8),rep("I",4), rep("I",4), rep("P", 32), rep("I", 4), rep("P",27), rep("I", 8), "P", rep("I", 4), rep("I", 8)), 

moult = c(rep("", 80), 0,0,10,20,rep("", 11),20,"","", 0,10,"", 20,rep("", 6) ),

 exp= c(rep("conc",8), rep("OvY", 12), rep("cut", 4), rep("OvY",4), rep("regen", 4), rep("OvY",8), rep("regen", 4), rep("OvY",4), rep("OvY", 12), rep("regen", 12), rep("OvY", 8), rep("moult", 4),rep("regen", 9), "OvY", "OvY", "moult",  "OvY", "OvY", "moult", "moult", "moult", "moult", rep("regen", 6) )

)


sampleinfo$flag <- FALSE
sampleinfo$flag[c(5,6,7,8,25,31,32, 54, 59, 66,67, 78,90, 97,101)] <- TRUE


#c(23,24,37,43,44, 54, 59, 66,67, 78,90, 97,101)

sampleinfo$type <- paste(sampleinfo$age, sampleinfo$reg, sep="")
sampleinfo$qual <- "ok"
sampleinfo$qual[c(25 , 31 , 32 , 49,  54 , 67  ,76,  90, 101, 104, 107)] <- "bad"
#sampleinfo$moult <- c(rep(NA, 80), 0,0,10,20,rep(NA, 11),20,NA,NA, 0,10,NA, 20,rep(NA, 6) )

#print("Samples as follows (all experiments)")
#print(paste("males: " sum()))

```

#Quality testing
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}

mc <- melt(ctg1to9)
mc$exp <- mc$value > 1
mc$qual <- mc$Var2 %in% sampleinfo$sample[sampleinfo$qual == "ok"]
mc$flag <- mc$Var2 %in% sampleinfo$sample[sampleinfo$flag == TRUE]
ggplot(mc, aes(y=value, x=Var1, colour=qual)) +  theme_bw() +  geom_point(alpha=0.3) +  facet_wrap(~Var2, ncol=12) +  scale_y_log10() +  scale_colour_manual(values=c("red3", "dark blue")) +  theme(axis.text.x = element_blank())


ggplot(mc, aes(y=value, x=Var2, colour=flag)) +  theme_bw() +  geom_point(alpha=0.1) +  scale_y_log10() +  scale_colour_manual(values=c("red3", "dark blue")) +  theme(axis.text.x = element_text(angle = 80, hjust =1, size=7))



```

#k-nearest neighbours approach to measuring sample quality
How can we objectively measure the quality of a sample? We'll try a simple machine learning approach, whereby we take our first 


```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}
#Take the first 4 cartridges only:
cdat <- as.data.frame(ctg1to9un)



orderval <- function(x) {
  x <- x[order(x)]
}

cdat.order <- apply(cdat, 2, order)
cdat.orderval <- apply(cdat, 2, orderval)


ts.order <- cdat.orderval[,1:48]
ts.orderval <- t(cdat.orderval[,1:48])
si <- subset(sampleinfo, sampleinfo$sample %in% colnames(ts.order))

ts.orderval.norm <- ts.orderval/rowMax(ts.orderval)

trainview<- melt(t(ts.orderval.norm))
trainview$flag <- trainview$Var2 %in% sampleinfo$sample[sampleinfo$flag == TRUE]

ggplot(data=trainview, aes(x=Var1, y=value, colour=flag))+
  geom_point()+
  scale_y_log10()+
  facet_wrap(~Var2)+
  ggtitle("kNN data quality testing: training dataset") +
  scale_colour_manual(values=c("forest green", "red3"))

es.orderval <- t(cdat.orderval[,49:108])
es.orderval.norm <- es.orderval/rowMax(es.orderval)

qualknn <- knn(train=ts.orderval.norm, test=es.orderval.norm, cl=si$flag, prob=TRUE, k=10)
-


preddf <- data.frame(sample=rownames(es.orderval), value=as.factor(qualknn), score= attr(qualknn, "prob"))

#testview$predval <- testview$Var2 %in% preddf$sample[preddf == TRUE]
  
  
testview<- as.data.frame(t(es.orderval.norm))
#testview$predval <- as.factor(qualknn)
#testview$testscore <- attr(qualknn, "prob")

mtestview <- melt(testview)
mtestview$predval <- mtestview$variable %in% preddf$sample[preddf$value == TRUE]
mtestview$order <- seq(1:195)
mtestview$predscore <- rep(preddf$score, each=nrow(testview))
mtestview$arbqual <- mtestview$variable %in% sampleinfo$sample[sampleinfo$qual == "ok"]

 
ggplot(data=mtestview, aes(x=order, y=value, colour=predscore))+
  geom_point()+
  scale_y_log10()+
  facet_wrap(~variable)+
  geom_text(inherit.aes=FALSE, aes(label=arbqual, x=100,y=0.5))+
  scale_color_distiller(palette="Spectral")


```

This won't do the job!
Let's try another approach




```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results="hide"}


ggplot(data=as.data.frame(ctg1to9), aes(x=C200))+
  geom_histogram()+
  scale_x_log10()



ggplot(data=mc, aes(x=value, fill=qual))+
  geom_histogram()+
  scale_x_log10()+
  facet_wrap(~Var2) +
  scale_fill_manual(values=c("red3", "dark blue"))



ggplot(data=mc, aes(x=value, fill=qual))+
  geom_histogram()+
  scale_x_log10()+
  facet_wrap(~Var2) +
  scale_fill_manual(values=c("red3", "dark blue"))

mcu <- melt(ctg1to9un[,1:6])



#mcu$exp <- mc$value > 1
#mcu$qual <- mc$Var2 %in% sampleinfo$sample[sampleinfo$qual == "ok"]

ggplot(data=mcu, aes(x=value))+
  geom_histogram()+
  scale_x_log10()+
  facet_wrap(~Var2) +
  scale_fill_manual(values=c("red3", "dark blue"))
mcb <- rbind(cbind(mc,t="norm") ,cbind(mcu, t="un"))

ggplot(data=mcu, aes(x=value, fill=Var2))+
  geom_histogram(alpha=0.5)+
  scale_x_log10()+
  scale_fill_manual(values=c("red3", "dark blue"))





```
